# Generated by Django 5.1.4 on 2025-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_end',
            new_name='end_dttm_aware',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_start',
            new_name='start_dttm_aware',
        ),
        migrations.AddField(
            model_name='event',
            name='end_dttm_naive',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_dttm_naive',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
