# Generated by Django 5.1.4 on 2025-03-16 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBuilder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_status', models.CharField(choices=[('STARTED', 'STARTED'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='STARTED', max_length=7)),
                ('build_fail_reason', models.CharField(blank=True, null=True)),
                ('build_start', models.DateTimeField(auto_now_add=True)),
                ('build_time', models.DurationField(blank=True, null=True)),
                ('user_input_text', models.TextField()),
                ('llm_raw_response', models.TextField(blank=True, null=True)),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_event_builders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EventBuilder',
                'verbose_name_plural': 'EventBuilders',
                'ordering': ['-build_start'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('built_at', models.DateTimeField()),
                ('summary', models.CharField(max_length=255)),
                ('start_dttm_aware', models.DateTimeField(blank=True, null=True)),
                ('start_dttm_naive', models.CharField(blank=True, max_length=25, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_dttm_aware', models.DateTimeField(blank=True, null=True)),
                ('end_dttm_naive', models.CharField(blank=True, max_length=25, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recurrence_rules', models.CharField(blank=True, max_length=255)),
                ('gcal_link', models.TextField(blank=True)),
                ('outlook_link', models.TextField(blank=True)),
                ('ics_data', models.TextField(blank=True)),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_events', to=settings.AUTH_USER_MODEL)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='multiple_event_creator.eventbuilder')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-built_at'],
            },
        ),
    ]
