# Generated by Django 5.1.4 on 2025-01-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=998)),
                ('body', models.TextField()),
                ('failed', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
