# Generated by Django 5.1.4 on 2025-01-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
